### ISSUE TITLE
Parker Weights: Cone Beam - Short Angle

### ISSUE THREAD

**Issue by tknopp** [JuliaImageRecon/Sinograms.jl#43]
After successfully reconstructing the slices of a flat panel cone beam dataset using the fan beam geometry (`SinoFanFlat`) I next tried out the full 3D dataset using `CtFanFlat`. Again, things went rather smoothly and it required just minor modifications which I could easily extract from the documentation.

However, with the FDK reconstruction I now get the same artifacts that I got with the fan beam geometry when using no parker weights. Therefore the question: Can it be that the parker weights for short angle 3D scans are currently not used?

Below is a screenshot. Upper left is the Sinograms.jl reconstruction and upper right the reconstruction provided by the scanner.

<img width="848" alt="Bildschirmfoto 2022-12-23 um 10 50 51" src="https://user-images.githubusercontent.com/3109172/209313877-8bc1d8f4-35ba-4318-ae60-26e7094b1a06.png">

**Comment by JeffFessler** [comment]
> Can it be that the parker weights for short angle 3D scans are currently not used?

Correct - I had not gotten around to implementing or testing that.  Sorry!
I will work on it pretty soon.

**Comment by tknopp** [comment]
Thanks, no hurry!

**Comment by tknopp** [comment]
Fixed by https://github.com/JuliaImageRecon/Sinograms.jl/pull/46, thanks!

**Comment by JeffFessler** [comment]
I hadn't closed it yet because #47 is a major overhaul that should be better yet, and I'm planning to wait to tag a new release when that is done.  Glad to hear #46 worked for you.   Previously I had built lots of it on `getproperty` and that turns out to be bad for type stability.  I'm completely eliminating that now...

**Comment by tknopp** [comment]
ok, then lets re-open.

**Comment by JeffFessler** [comment]
Ok, now I have merged #47 and it passes all the tests and the docs look to build correctly, so I'll close this and tag 0.4.
The only annoying thing is that codecov does not seem to track `Threads.@threads` properly:
https://app.codecov.io/gh/JuliaImageRecon/Sinograms.jl/blob/main/src/fbp3/cbct-back.jl
so I have to settle for 99% instead of 100% coverage and the scarlet `x` for failed CI ☹️
It is quite possible that this massive overhaul will have broken something so when you have a chance please try the new version on you short CBCT data and let me know of any issues.
